# **TENSORS**
Tensors are a specialized data structure that are very similar to arrays and matrices.


In [1]:
import torch
import numpy as np

## Initializing a Tensor

In [2]:
# Directly from data
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
print(x_data)

# Directly from Numpy
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(x_np)

# From another tensor
x_ones = torch.ones_like(x_data) # Retains the propeerties (shape, datatype) of x_data 
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # Overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

# Witch random or constant values
shape = (2, 3)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

tensor([[1, 2],
        [3, 4]])
tensor([[1, 2],
        [3, 4]])
Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.6817, 0.8133],
        [0.3934, 0.1572]]) 

Random Tensor: 
 tensor([[0.3970, 0.7019, 0.8641],
        [0.4363, 0.8291, 0.7281]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


## ATTRIBUTES OF A TENSOR

In [3]:
tensor = torch.rand(3, 4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


## OPERATIONS ON TENSORS

In [4]:
# We move our tensor to the GPU if available
if torch.cuda.is_available():
  tensor = tensor.to('cuda')

**Standard Numpy-like indexing and slicing**

In [5]:
tensor = torch.rand(size=(4,4))

print('First row: ',tensor[0])
print('First column: ', tensor[:, 0])
print('Last column:', tensor[..., -1])
tensor[:,1] = 0.0
print(tensor)

First row:  tensor([0.6260, 0.6266, 0.3481, 0.6259])
First column:  tensor([0.6260, 0.2637, 0.8976, 0.4320])
Last column: tensor([0.6259, 0.2678, 0.2514, 0.2565])
tensor([[0.6260, 0.0000, 0.3481, 0.6259],
        [0.2637, 0.0000, 0.8641, 0.2678],
        [0.8976, 0.0000, 0.3864, 0.2514],
        [0.4320, 0.0000, 0.0120, 0.2565]])


**Joining tensors**

In [6]:
tensor = torch.ones(size=(1, 2))

t1 = torch.cat([tensor, tensor, tensor], dim=1) # All tensors must either have the same shape or be empty.
print(t1)

tensor([[1., 1., 1., 1., 1., 1.]])


**Arithmetic operations**

In [7]:
# Computes matrix multiplication between 2 tensors. y1, y2 and y2 will have the same value
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=y3)

print("Y1", y1)
print("Y2", y2)
print("Y3", y3)

Y1 tensor([[2.]])
Y2 tensor([[2.]])
Y3 tensor([[2.]])


In [8]:
# Compute the element-wise product, z1, z2 and z3 will be have the same value
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

print("Z1", z1)
print("Z2", z2)
print("Z3", z3)

Z1 tensor([[1., 1.]])
Z2 tensor([[1., 1.]])
Z3 tensor([[1., 1.]])


In [9]:
# Single-element tensors
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

2.0 <class 'float'>


In [10]:
# In-place operations, they are denoted by a '_' suffix
print(tensor, '\n')
tensor.add_(5)
print(tensor)

tensor([[1., 1.]]) 

tensor([[6., 6.]])


In [12]:
# NumPy array yo Tensor
n = np.ones(5)
t = torch.from_numpy(n)
print(t)
# Changes in the NumPy array reflects in the tensor.
np.add(n, 1, out=n)
print(n)
print(t)

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
