In [1]:
import numpy as np
import pandas as pd

In [2]:
# setup
pd.options.display.float_format = "{:.2f}".format
np.set_printoptions(precision=2)

In [5]:
x1 = np.random.rand(2, 5) * 10
x1

array([[6.27, 8.73, 9.62, 2.06, 0.28],
       [7.97, 0.09, 7.95, 9.61, 3.61]])

In [4]:
x2 = np.random.rand(2, 5) * -1
x2

array([[-0.78, -0.76, -0.51, -0.88, -0.95],
       [-0.69, -0.7 , -0.22, -0.11, -0.27]])

In [7]:
# Concatenar dos arrays de Numpy
res = np.concatenate([x1, x2])
print(res.shape)
res

(4, 5)


array([[ 6.27,  8.73,  9.62,  2.06,  0.28],
       [ 7.97,  0.09,  7.95,  9.61,  3.61],
       [-0.78, -0.76, -0.51, -0.88, -0.95],
       [-0.69, -0.7 , -0.22, -0.11, -0.27]])

In [8]:
# concatenar sobre las columnas
res = np.concatenate([x1, x2], axis=1)
print(res.shape)
res

(2, 10)


array([[ 6.27,  8.73,  9.62,  2.06,  0.28, -0.78, -0.76, -0.51, -0.88,
        -0.95],
       [ 7.97,  0.09,  7.95,  9.61,  3.61, -0.69, -0.7 , -0.22, -0.11,
        -0.27]])

**CONCATENANDO SERIES**

In [9]:
s1 = pd.Series(x1[0], index=["a", "b", "c", "d", "e"])
s1

a   6.27
b   8.73
c   9.62
d   2.06
e   0.28
dtype: float64

In [10]:
s2 = pd.Series(x2[0], index=["c", "d", "e", "f", "g"])
s2

c   -0.78
d   -0.76
e   -0.51
f   -0.88
g   -0.95
dtype: float64

In [11]:
# concatenar dos series
pd.concat([s1, s2])

a    6.27
b    8.73
c    9.62
d    2.06
e    0.28
c   -0.78
d   -0.76
e   -0.51
f   -0.88
g   -0.95
dtype: float64

In [12]:
# concatenar sobre la columnas, se crea un dataframe
# los índices repetidos estarán definidos en ambas columnas
pd.concat([s1, s2], axis=1)

0     1
a 6.27   NaN
b 8.73   NaN
c 9.62 -0.78
d 2.06 -0.76
e 0.28 -0.51
f  NaN -0.88
g  NaN -0.95

In [14]:
# quitar índice de una serie
s1.reset_index(drop=True)

0   6.27
1   8.73
2   9.62
3   2.06
4   0.28
dtype: float64

In [15]:
# concatenar con los índices reseteados
pd.concat([s1.reset_index(drop=True), s2.reset_index(drop=True)], axis=1)

0     1
0 6.27 -0.78
1 8.73 -0.76
2 9.62 -0.51
3 2.06 -0.88
4 0.28 -0.95

**CONCATENAR DATAFRAMES**

In [16]:
# crear dataframe con números aleatorios
df1 = pd.DataFrame(np.random.rand(3, 2) * 10, columns=["a", "b"])
df1

a    b
0 4.59 4.03
1 3.25 9.10
2 9.21 3.44

In [17]:
# crear dataframe con números aleatorios negativos
df2 = pd.DataFrame(np.random.rand(3, 2) * -1, columns=["a", "b"], index=[2, 3, 4])
df2

a     b
2 -0.85 -0.07
3 -0.89 -0.84
4 -0.98 -0.77

In [18]:
pd.concat([df1, df2])
# notar que se repite el índice compartido (2)

a     b
0  4.59  4.03
1  3.25  9.10
2  9.21  3.44
2 -0.85 -0.07
3 -0.89 -0.84
4 -0.98 -0.77

In [21]:
# concatenar sobre las columnas
pd.concat([df1, df2], axis=1)


a    b     a     b
0 4.59 4.03   NaN   NaN
1 3.25 9.10   NaN   NaN
2 9.21 3.44 -0.85 -0.07
3  NaN  NaN -0.89 -0.84
4  NaN  NaN -0.98 -0.77

In [22]:
# concatenar solo sobre índices compartidos
pd.concat([df1, df2], axis=1, join="inner")

a    b     a     b
2 9.21 3.44 -0.85 -0.07

In [23]:
# concatenar reseteando los índices
pd.concat(
    [df1.reset_index(drop=True), df2.reset_index(drop=True)], 
    axis=1
)

a    b     a     b
0 4.59 4.03 -0.85 -0.07
1 3.25 9.10 -0.89 -0.84
2 9.21 3.44 -0.98 -0.77

In [24]:
# usando append para concatenar
df1.append(df2)

/tmp/ipykernel_10298/1833280361.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1.append(df2)


a     b
0  4.59  4.03
1  3.25  9.10
2  9.21  3.44
2 -0.85 -0.07
3 -0.89 -0.84
4 -0.98 -0.77