### Situation

Breast cancer - original one from: https://archive.ics.uci.edu/ml/datasets/breast+cancer

When a patient has a benign or malign tumor.


## XGBoost

### Importing libs

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

### Dataset

In [4]:
dataset_path = "../../../../datasets/ml_az_course/007_breast_cancer.csv"

df = pd.read_csv(dataset_path)
df


Sample code number  Clump Thickness  Uniformity of Cell Size  \
0               1000025                5                        1   
1               1002945                5                        4   
2               1015425                3                        1   
3               1016277                6                        8   
4               1017023                4                        1   
..                  ...              ...                      ...   
678              776715                3                        1   
679              841769                2                        1   
680              888820                5                       10   
681              897471                4                        8   
682              897471                4                        8   

     Uniformity of Cell Shape  Marginal Adhesion  Single Epithelial Cell Size  \
0                           1                  1                            2   
1                           4                  5                            7   
2                           1                  1                            2   
3                           8                  1                            3   
4                           1                  3                            2   
..                        ...                ...                          ...   
678                         1                  1                            3   
679                         1                  1                            2   
680                        10                  3                            7   
681                         6                  4                            3   
682                         8                  5                            4   

     Bare Nuclei  Bland Chromatin  Normal Nucleoli  Mitoses  Class  
0              1                3                1        1      2  
1             10                3                2        1      2  
2              2                3                1        1      2  
3              4                3                7        1      2  
4              1                3                1        1      2  
..           ...              ...              ...      ...    ...  
678            2                1                1        1      2  
679            1                1                1        1      2  
680            3                8               10        2      4  
681            4               10                6        1      4  
682            5               10                4        1      4  

[683 rows x 11 columns]

In [5]:
x = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

In [11]:
y[:4]

array([2, 2, 2, 2])

In [13]:
mapping = {2: 0, 4: 1}

for idx, v in enumerate(y):
    y[idx] = mapping[v]

In [14]:
y[:4]

array([0, 0, 0, 0])

### Splitting the dataset

In [15]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=42)

### Training

In [16]:
from xgboost import XGBClassifier

classifier = XGBClassifier()

classifier.fit(x_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              n_estimators=100, n_jobs=None, num_parallel_tree=None,
              predictor=None, random_state=None, ...)

### Making the confusion matrix

In [17]:
from sklearn.metrics import confusion_matrix, accuracy_score

preds = classifier.predict(X=x_test)
confusion_matrix(y_true=y_test, y_pred=preds)

array([[102,   1],
       [  5,  63]])

In [18]:
accuracy_score(y_true=y_test, y_pred=preds)

0.9649122807017544

comparable to: sklearn.naive_bayes.GaussianNB

### Cross-validation

In [19]:
from sklearn.model_selection import cross_val_score


accuracies = cross_val_score(
    estimator=classifier, X=x_train, y=y_train, cv=10
)

print("accuracy: {:.2f} %".format(accuracies.mean() * 100))
print("std {:.2f} %".format(accuracies.std()))

accuracy: 97.06 %
std 0.02 %
